branches:
  only:
    - master
    - dev
    - /^hotfix.*$/
    - /^feature.*$/

notifications:
  email:
    on_success: change
    on_failure: always

language: swift

stages:
  - Tests

jobs:
  include:
    - stage: Tests
      os: osx
      osx_image: xcode12
      name: Unit Tests
      script: fastlane ios tests
      after_success: bash <(curl -s https://codecov.io/bash)