name: CI

on:
  push:
    branches:
    - master
    - dev
    - /^hotfix.*$/
    - /^feature.*$/
  pull_request:
    branches:
    - master

jobs:
  tests:
    name: Unit Tests
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run test
      run: fastlane ios tests
    - name: Upload to Codecov
      run: bash <(curl -s https://codecov.io/bash)
  compatibility:
    name: Compatibility Tests
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: fastlane ios compatibilityTests
      run: fastlane ios compatibilityTests
